import { finalMonth, topics } from '../data/content'

export function Sections(){return <>
  <section className="section intro" id="about"><div className="sectionInner split"><div><p className="kicker">Почему этот курс важен</p><h2>Мужчине важно понимать, куда и зачем он идёт</h2></div><p className="sectionText">Курс объединяет ключевые темы мужского развития: ответственность, отношения, лидерство, предназначение и внутренние ориентиры. Обучение проходит последовательно, в сопровождении кураторов и сообщества участников.</p></div></section>
  <section className="section" id="audience"><div className="sectionInner"><p className="kicker">Для кого курс</p><h2>Для мужчин, которые хотят двигаться осознанно</h2><div className="cards three"><Card n="01" t="Новые слушатели" d="Для тех, кто впервые знакомится с проектом и ищет системный путь развития."/><Card n="02" t="Участники прошлых программ" d="Для тех, кто хочет продолжить работу над собой в новом формате и круге тем."/><Card n="03" t="Мужчины в поиске ориентиров" d="Для тех, кому важны зрелость, ответственность, отношения и предназначение."/></div></div></section>
  <section className="section program" id="program"><div className="sectionInner"><p className="kicker">Программа</p><h2>Основные темы курса</h2><div className="topicGrid">{topics.map((t,i)=><div className="topic" key={t}><span>{String(i+1).padStart(2,'0')}</span><h3>{t}</h3></div>)}</div><div className="finalMonth"><div><p className="kicker">Заключительный месяц</p><h3>Дополнительный блок</h3></div><div className="chips">{finalMonth.map(x=><span key={x}>{x}</span>)}</div></div></div></section>
  <section className="section" id="format"><div className="sectionInner"><p className="kicker">Как проходит обучение</p><h2>Полностью онлайн — с живым взаимодействием</h2><div className="cards three"><Card n="01" t="Zoom-встречи" d="Живые онлайн-встречи в рамках курса."/><Card n="02" t="Общий чат" d="Общение с участниками и обмен опытом между встречами."/><Card n="03" t="Кураторы" d="Сопровождение и поддержка участников в общем чате."/></div></div></section>
  <section className="section approach"><div className="sectionInner split"><div><p className="kicker">Особенности подхода</p><h2>Не только знания, но и пространство развития</h2></div><div className="list"><p>Системная последовательность тем</p><p>Живые встречи вместо самостоятельного просмотра записей</p><p>Сообщество участников и поддержка кураторов</p><p>Три месяца последовательной работы</p></div></div></section>
  <section className="section muted"><div className="sectionInner"><p className="kicker">Преподаватели</p><h2>Команда курса</h2><p className="placeholder">Информация о преподавателях будет добавлена после утверждения командой проекта.</p></div></section>
  <section className="section"><div className="sectionInner"><p className="kicker">Результат участия</p><h2>Целостное понимание направления своего развития</h2><p className="sectionText narrow">По завершении курса участник получает системное представление о ключевых темах мужского развития, ценности наставничества и сообщества, а также ориентиры для дальнейшего обучения.</p></div></section>
  <section className="section muted"><div className="sectionInner"><p className="kicker">Отзывы</p><h2>Истории участников</h2><p className="placeholder">Раздел подготовлен технически и будет наполнен после появления утвержденных отзывов.</p></div></section>
  <section className="section faq"><div className="sectionInner"><p className="kicker">Частые вопросы</p><h2>Что важно знать до старта</h2><details><summary>В каком формате проходит курс?</summary><p>Курс проходит полностью онлайн. Встречи проводятся в Zoom, общение продолжается в общем чате.</p></details><details><summary>Сколько длится обучение?</summary><p>Продолжительность курса — три месяца.</p></details><details><summary>Можно ли участвовать новому слушателю?</summary><p>Да. Курс рассчитан как на новых слушателей, так и на участников предыдущих образовательных проектов.</p></details></div></section>
</>}
function Card({n,t,d}:{n:string;t:string;d:string}){return <article className="card"><span>{n}</span><h3>{t}</h3><p>{d}</p></article>}
