import { contacts, finalMonth, socialNetworks, topics } from '../data/content'

export function Sections(){return <>
  <section className="section intro" id="about"><div className="sectionInner split"><div><p className="kicker">Почему этот курс важен</p><h2>Мужчине важно понимать, куда и зачем он идёт</h2></div><p className="sectionText">Курс объединяет ключевые темы мужского развития: ответственность, отношения, лидерство, предназначение и внутренние ориентиры. Обучение проходит последовательно, в сопровождении кураторов и сообщества участников.</p></div></section>
  <section className="section" id="audience"><div className="sectionInner"><p className="kicker">Для кого курс</p><h2>Для мужчин, которые хотят двигаться осознанно</h2><div className="cards three"><Card n="01" t="Новые слушатели" d="Для тех, кто впервые знакомится с проектом и ищет системный путь развития."/><Card n="02" t="Участники прошлых программ" d="Для тех, кто хочет продолжить работу над собой в новом формате и круге тем."/><Card n="03" t="Мужчины в поиске ориентиров" d="Для тех, кому важны зрелость, ответственность, отношения и предназначение."/></div></div></section>
  <section className="section program" id="program"><div className="sectionInner"><p className="kicker">Программа</p><h2>Основные темы курса</h2><div className="topicGrid">{topics.map((t,i)=><div className="topic" key={t}><span>{String(i+1).padStart(2,'0')}</span><h3>{t}</h3></div>)}</div><div className="finalMonth"><div><p className="kicker">Заключительный месяц</p><h3>Дополнительный блок</h3></div><div className="chips">{finalMonth.map(x=><span key={x}>{x}</span>)}</div></div></div></section>
  <section className="section" id="format"><div className="sectionInner"><p className="kicker">Как проходит обучение</p><h2>Полностью онлайн — с живым взаимодействием</h2><div className="cards three"><Card n="01" t="Zoom-встречи" d="Живые онлайн-встречи в рамках курса."/><Card n="02" t="Общий чат" d="Общение с участниками и обмен опытом между встречами."/><Card n="03" t="Кураторы" d="Сопровождение и поддержка участников в общем чате."/></div></div></section>
  <section className="section donation" id="donation"><div className="sectionInner donationInner"><div><p className="kicker">Условия участия</p><h2>Курс проходит за добровольные пожертвования</h2></div><div className="donationText"><p>Размер пожертвования вы определяете самостоятельно.</p><p>Фиксированной стоимости участия нет. Вклад каждого участника остаётся свободным и добровольным.</p></div></div></section>
  <section className="section approach"><div className="sectionInner split"><div><p className="kicker">Особенности подхода</p><h2>Не только знания, но и пространство развития</h2></div><div className="list"><p>Системная последовательность тем</p><p>Живые встречи вместо самостоятельного просмотра записей</p><p>Сообщество участников и поддержка кураторов</p><p>Три месяца последовательной работы</p></div></div></section>
  <section className="section muted"><div className="sectionInner"><p className="kicker">Преподаватели</p><h2>Команда курса</h2><p className="placeholder">Информация о преподавателях будет добавлена после утверждения командой проекта.</p></div></section>
  <section className="section"><div className="sectionInner"><p className="kicker">Результат участия</p><h2>Целостное понимание направления своего развития</h2><p className="sectionText narrow">По завершении курса участник получает системное представление о ключевых темах мужского развития, ценности наставничества и сообщества, а также ориентиры для дальнейшего обучения.</p></div></section>
  <section className="section muted"><div className="sectionInner"><p className="kicker">Отзывы</p><h2>Истории участников</h2><p className="placeholder">Раздел подготовлен технически и будет наполнен после появления утвержденных отзывов.</p></div></section>
  <section className="section faq"><div className="sectionInner"><p className="kicker">Частые вопросы</p><h2>Что важно знать до старта</h2><details><summary>В каком формате проходит курс?</summary><p>Курс проходит полностью онлайн. Встречи проводятся в Zoom, общение продолжается в общем чате.</p></details><details><summary>Сколько длится обучение?</summary><p>Продолжительность курса — три месяца.</p></details><details><summary>Можно ли участвовать новому слушателю?</summary><p>Да. Курс рассчитан как на новых слушателей, так и на участников предыдущих образовательных проектов.</p></details></div></section>
  <section className="section contacts" id="contacts"><div className="sectionInner"><p className="kicker">Связаться с нами</p><h2>Если у вас остались вопросы, вы можете связаться с нами</h2><div className="contactCountries"><ContactCountry title="Россия" items={contacts.russia}/><ContactCountry title="Казахстан" items={contacts.kazakhstan}/></div><div className="socialBlock"><div><p className="kicker">Социальные сети</p><h3>Следите за новостями проекта</h3></div><div className="socialGrid">{socialNetworks.map(network=><div className="socialPlaceholder" key={network.id} aria-disabled="true"><SocialIcon id={network.id}/><span>{network.label}</span><small>Ссылка будет добавлена</small></div>)}</div></div></div></section>
</>}

function Card({n,t,d}:{n:string;t:string;d:string}){return <article className="card"><span>{n}</span><h3>{t}</h3><p>{d}</p></article>}

function ContactCountry({title,items}:{title:string;items:{name:string;phone:string;href:string}[]}){
  return <div className="contactCountry"><h3>{title}</h3>{items.map(item=><div className="contactRow" key={item.name}><strong>{item.name}</strong>{item.href?<a href={item.href}>{item.phone}</a>:<span className="contactPending">{item.phone}</span>}</div>)}</div>
}

function SocialIcon({id}:{id:string}){
  const common={width:28,height:28,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round' as const,strokeLinejoin:'round' as const,'aria-hidden':true}
  if(id==='telegram') return <svg {...common}><path d="M21 3 3.8 10.1c-1.2.5-1.2 1.2-.2 1.5l4.4 1.4 1.7 5.3c.2.7.1 1 .8 1 .5 0 .8-.2 1-.4l2.5-2.4 5.1 3.8c.9.5 1.6.3 1.8-.9L24 4.6C24.3 3.3 23.5 2.7 21 3Z"/></svg>
  if(id==='instagram') return <svg {...common}><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>
  if(id==='youtube') return <svg {...common}><path d="M22 12s0-3.4-.4-5c-.2-1-1-1.8-2-2C17.9 4.5 12 4.5 12 4.5s-5.9 0-7.6.5c-1 .2-1.8 1-2 2C2 8.6 2 12 2 12s0 3.4.4 5c.2 1 1 1.8 2 2 1.7.5 7.6.5 7.6.5s5.9 0 7.6-.5c1-.2 1.8-1 2-2 .4-1.6.4-5 .4-5Z"/><path d="m10 9 5 3-5 3Z"/></svg>
  return <svg {...common}><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m10 9 5 3-5 3Z"/></svg>
}
